export const movieList = [{
  "id": "001",
  "title": "12 Angry Men",
  "year": "1957",
  "description": "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
  "image": "images/12-angry-men.jpg",
},
{
  "id": "002",
  "title": "42",
  "year": "2013",
  "description": "In 1946, Branch Rickey (Harrison Ford) put himself at the forefront of history when he signed Jackie Robinson (Chadwick Boseman) to the team, breaking Major League Baseball's infamous color line. Facing unabashed racism from every side, Robinson was forced to demonstrate tremendous courage and restraint by not reacting, instead letting his talent on the field do the talking — ultimately winning over fans and his teammates, silencing his critics, and paving the way for others to follow. In 1997, Major League Baseball retired the number 42 for all teams, making it the first number in sports to be universally retired.",
  "image": "images/42.jpeg",
},
{
  "id": "003",
  "title": "The Adjustment Bureau",
  "year": "2011",
  "description": "Academy Award® nominee Matt Damon (The Bourne trilogy) stars in this action thriller about a man who glimpses the future Fate has planned for him – and chooses to fight for his own destiny. Battling the powerful Adjustment Bureau across, under and through the streets of New York, he risks his destined greatness to be with the only woman he's ever loved (Emily Blunt: The Young Victoria, The Devil Wears Prada). Based on a story by the legendary Philip K. Dick (Total Recall, Minority Report and Blade Runner), The Adjustment Bureau is “entertaining and thought-provoking”. — Katey Rich, CINEMABLEND.COM",
  "image": "images/the-adjustment-bureau.jpg",
},
{
  "id": "004",
  "title": "50 First Dates",
  "year": "2004",
  "description": "Henry is a player skilled at seducing women. But when this veterinarian meets Lucy, a girl with a quirky problem when it comes to total recall, he realizes it's possible to fall in love all over again…and again, and again. That's because the delightful Lucy has no short-term memory, so Henry must woo her day after day until he finally sweeps her off her feet.",
  "image": "images/50-first-dates.jpg",
},
{
  "id": "005",
  "title": "Air Force One",
  "year": "1997",
  "description": "The fate of the nation rests on the courage of one man. Harrison Ford and Gary Oldman star in two-time Oscar® nominee Wolfgang Petersen's gripping thriller about an uncompromising U.S. President who has just told the world he will not negotiate with terrorists. When Russian neo-nationalists hijack Air Force One, the world's most secure and extraordinary aircraft, the President is faced with a nearly impossible decision to give in to terrorist demands or sacrifice not only the country's dignity, but the lives of his wife and daughter.",
  "image": "images/air-force-one.jpg",
},
{
  "id": "006",
  "title": "Aladdin",
  "year": "1992",
  "description": "Princess Jasmine grows tired of being forced to remain in the palace, so she sneaks out into the marketplace, in disguise, where she meets street-urchin Aladdin. The couple falls in love, although Jasmine may only marry a prince. After being thrown in jail, Aladdin becomes embroiled in a plot to find a mysterious lamp, with which the evil Jafar hopes to rule the land.",
  "image": "images/alladin-cartoon.jpg",
},
{
  "id": "007",
  "title": "Aladdin",
  "year": "2019",
  "description": "From Disney comes the thrilling and vibrant live-action adaptation of the animated classic Aladdin, the exciting tale of the charming street rat Aladdin, the self-determined Princess Jasmine and the Genie who may be the key to their future. Directed by Guy Ritchie, Aladdin features an all-star cast including Will Smith as the larger-than-life Genie, Mena Massoud as the clever scoundrel Aladdin and Naomi Scott as Jasmine, the beautiful, courageous princess of Agrabah.",
  "image": "images/alladin.jpg",
},
{
  "id": "008",
  "title": "Alice in Wonderland",
  "year": "1951",
  "description": "On a golden afternoon, young Alice follows a White Rabbit, who disappears down a nearby rabbit hole. Quickly following him, she tumbles into the burrow - and enters the merry, topsy-turvy world of Wonderland! Memorable songs and whimsical escapades highlight Alice's journey, which culminates in a madcap encounter with the Queen of Hearts - and her army of playing cards!",
  "image": "images/alice-in-wonderland-cartoon.png",
},
{
  "id": "009",
  "title": "Alice In Wonderland",
  "year": "2010",
  "description": "Tumble down the rabbit hole with Alice for a fantastical adventure! Inviting and magical, Alice In Wonderland is an imaginative new twist on one of the most beloved stories of all time. Alice (Mia Wasikowska), now 19 years old, returns to the whimsical world she first entered as a child and embarks on a journey to discover her true destiny. This Wonderland is a world beyond your imagination and unlike anything you've seen before. The extraordinary characters you've loved come to life richer and more colorful than ever. There's the Mad Hatter (Johnny Depp), the White Queen (Anne Hathaway), the Red Queen (Helena Bonham Carter), the White Rabbit (Michael Sheen) and more. A triumphant cinematic experience, Alice In Wonderland is an incredible feast for your eyes, ears and heart that will captivate audiences of all sizes.",
  "image": "images/alice-in-wonderland.jpg",
},
{
  "id": "010",
  "title": "The Amazing Spider-Man",
  "year": "2012",
  "description": "Peter Parker is going back to high school in The Amazing Spider-Man as a teenager dealing with both contemporary human problems and amazing super-human crises.",
  "image": "images/the-amazing-spiderman.jpg",
},
{
  "id": "011",
  "title": "Angels in the Outfield",
  "year": "1994",
  "description": "Roger is a foster child whose irresponsible father promises to get his act together when Roger's favourite baseball team, the California Angels, wins the pennant. The problem is that the Angels are in last place, so Roger prays for help to turn the team around. Sure enough, his prayers are answered in the form of angel Al.",
  "image": "images/angels-in-the-outfield.jpeg",
},
{
  "id": "012",
  "title": "The Apartment",
  "year": "1960",
  "description": "Bud Baxter is a minor clerk in a huge New York insurance company, until he discovers a quick way to climb the corporate ladder. He lends out his apartment to the executives as a place to take their mistresses. Although he often has to deal with the aftermath of their visits, one night he's left with a major problem to solve.M",
  "image": "images/the-apartment.jpg",
},
{
  "id": "013",
  "title": "The Aristocats",
  "year": "1970",
  "description": "Everybody wants to be a cat! Disney’s unforgettable classic The Aristocats swings like never before in high definition. Share all the heart, humor and irresistible music of this timeless movie with your family. In the heart of Paris, a kind and eccentric millionaires wills her entire estate to Duchess, her high-society cat and her three kittens. When her greedy, bumbling butler attempts the ultimate catnap caper, the rough-and-tumble alley cat Thomas O’Malley and his band of swingin’ jazz cats must save the day. It’s the purr-fect blend of comedy and adventure.",
  "image": "images/the-aristocats.jpg",
},
{
  "id": "014",
  "title": "As Dreamers Do",
  "year": "2014",
  "description": "The early life of Walt Disney is explored in this family film with an art house twist. Though his reality was often dark, it was skewed by his ever growing imagination and eternal optimism.",
  "image": "images/as-dreamers-do.jpg",
},
{
  "id": "015",
  "title": "August Rush",
  "year": "2007",
  "description": "A drama with fairy tale elements, where an orphaned musical prodigy uses his gift as a clue to finding his birth parents.",
  "image": "images/august-rush.jpg",
},
{
  "id": "016",
  "title": "Avatar",
  "year": "2009",
  "description": "In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.",
  "image": "images/avatar.jpg",
},
{
  "id": "017",
  "title": "The Avengers",
  "year": "2012",
  "description": "When an unexpected enemy emerges and threatens global safety and security, Nick Fury, director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster. Spanning the globe, a daring recruitment effort begins!",
  "image": "images/the-avengers.jpg",
},
{
  "id": "018",
  "title": "Avengers: Age of Ultron",
  "year": "2015",
  "description": "Marvel Studios presents “Avengers: Age of Ultron,” the epic follow-up to the biggest Super Hero movie of all time. When Tony Stark tries to jumpstart a dormant peacekeeping program, things go awry and Earth’s Mightiest Heroes, including Iron Man, Captain America, Thor, The Incredible Hulk, Black Widow and Hawkeye, are put to the ultimate test as the fate of the planet hangs in the balance. As the villainous Ultron emerges, it is up to The Avengers to stop him from enacting his terrible plans, and soon uneasy alliances and unexpected action pave the way for an epic and unique global adventure.",
  "image": "images/avengers-ultron.jpg",
},
{
  "id": "019",
  "title": "Back to the Future",
  "year": "1985",
  "description": "Eighties teenager Marty McFly is accidentally sent back in time to 1955, inadvertently disrupting his parents' first meeting and attracting his mother's romantic interest. Marty must repair the damage to history by rekindling his parents' romance and - with the help of his eccentric inventor friend Doc Brown - return to 1985.",
  "image": "images/back-to-the-future.jpg",
},
{
  "id": "020",
  "title": "Back to the Future Part II",
  "year": "1989",
  "description": "Marty and Doc are at it again in this wacky sequel to the 1985 blockbuster as the time-traveling duo head to 2015 to nip some McFly family woes in the bud. But things go awry thanks to bully Biff Tannen and a pesky sports almanac. In a last-ditch attempt to set things straight, Marty finds himself bound for 1955 and face to face with his teenage parents -- again.",
  "image": "images/back-to-the-future-2.jpg",
},
{
  "id": "021",
  "title": "Back to the Future Part III",
  "year": "1990",
  "description": "The final installment of the Back to the Future trilogy finds Marty digging the trusty DeLorean out of a mineshaft and looking up Doc in the Wild West of 1885. But when their time machine breaks down, the travelers are stranded in a land of spurs. More problems arise when Doc falls for pretty schoolteacher Clara Clayton, and Marty tangles with Buford Tannen.",
  "image": "images/back-to-the-future-3.jpg",
},
{
  "id": "022",
  "title": "Batman Begins",
  "year": "2005",
  "description": "Driven by tragedy, billionaire Bruce Wayne dedicates his life to uncovering and defeating the corruption that plagues his home, Gotham City. Unable to work within the system, he instead creates a new identity, a symbol of fear for the criminal underworld - The Batman.",
  "image": "images/batman-begins.jpg",
},
{
  "id": "023",
  "title": "A Beautiful Day In the Neighborhood",
  "year": "2019 ",
  "description": "Tom Hanks portrays Mister Rogers in A Beautiful Day in the Neighborhood, a timely story of kindness triumphing over cynicism, based on the true story of a real-life friendship between Fred Rogers and journalist Tom Junod. After a jaded magazine writer (Emmy® winner Matthew Rhys, 2018 Best Actor in a Drama Series, The Americans) is assigned a profile of Fred Rogers, he overcomes his skepticism, learning about kindness, love and forgiveness from America’s most beloved neighbor.",
  "image": "images/a-beautiful-day-in-the-neighborhood.jpg",
},
{
  "id": "024",
  "title": "Beauty and the Beast",
  "year": "2017",
  "description": "The story and characters you know and love come to spectacular life in the live-action adaptation of Disney’s animated classic Beauty and the Beast, a cinematic event celebrating one of the most beloved tales ever told. Experience the fantastic journey of Belle, a bright, beautiful and independent young woman who is taken prisoner by a Beast in his castle. Despite her fears, she befriends the castle’s enchanted staff, and learns to look beyond the Beast’s hideous exterior and realize the kind heart of the true Prince within.",
  "image": "images/beauty-and-the-beast.jpeg",
},

{
  "id": "025",
  "title": "Bee Movie",
  "year": "2007",
  "description": "Barry B. Benson, a bee who has just graduated from college, is disillusioned at his lone career choice: making honey. On a special trip outside the hive, Barry's life is saved by Vanessa, a florist in New York City. As their relationship blossoms, he discovers humans actually eat honey, and subsequently decides to sue us.",
  "image": "images/bee-movie.jpg",
},
{
  "id": "026",
  "title": "Big",
  "year": "1988",
  "description": "At a carnival, young Josh Baskin (Tom Hanks) wishes he was big – only to awake the next morning and discover he is! With the help of his friend Billy, Josh lands a job at a toy company but the more he experiences being an adult, the more Josh longs for the simple joys of childhood.",
  "image": "images/big.jpg",
},
{
  "id": "027",
  "title": "Big Hero 6",
  "year": "2014",
  "description": "From Walt Disney Animation Studios comes Big Hero 6, an action-comedy adventure about brilliant robotics prodigy Hiro Hamada, who finds himself in the grips of a criminal plot that threatens to destroy the fast-paced, high-tech city of San Fransokyo. With the help of his closest companion – a robot named Baymax – Hiro joins forces with a reluctant team of first-time crime fighters on a mission to save their city.",
  "image": "images/big-hero-6.jpg",
},
{
  "id": "028",
  "title": "Black Panther",
  "year": "2018",
  "description": "After the death of his father, the king of Wakanda, young T'Challa returns home to the isolated high-tech African nation to succeed to the throne and take his rightful place as king. But when a powerful enemy reappears, T'Challa's mettle as king – and Black Panther – is tested when he’s drawn into a formidable conflict that puts the fate of Wakanda and the entire world at risk. Faced with treachery and danger, he must release the full power of Black Panther to defeat his foes and secure the safety of his people and their way of life.",
  "image": "images/black-panther.jpg",
},
{
  "id": "029",
  "title": "The Blind Side",
  "year": "2009",
  "description": "Oversized African-American, Michael Oher, the teen from across the tracks and a broken home, has nowhere to sleep at age 16. Taken in by an affluent Memphis couple, Michael embarks on a remarkable rise to play for the NFL.",
  "image": "images/the-blind-side.jpg",
},
{
  "id": "030",
  "title": "Bohemian Rhapsody",
  "year": "2018",
  "description": "Bohemian Rhapsody is an enthralling celebration of Queen, their music, and their extraordinary lead singer Freddie Mercury, who defied stereotypes and convention to become one of history’s most beloved entertainers. Following Queen’s meteoric rise, their revolutionary sound and Freddie’s solo career, the film also chronicles the band’s reunion, and one of the greatest performances in rock history.",
  "image": "images/bohemian-rhapsody.jpg",
},
{
  "id": "031",
  "title": "Bolt",
  "year": "2008",
  "description": "From Walt Disney Pictures comes an animated comedy adventure featuring a super-dog named BOLT (voice of John Travolta), whose days are filled with danger and intrigue -at least until the cameras stop rolling. When the star of a hit TV show is accidentally shipped from his Hollywood soundstage to New York City, he begins his biggest adventure yet - a cross-country journey through the real world to get back to his owner and co-star, Penny (voice of Miley Cyrus. Armed only with the delusions that all his amazing feats and powers are real, and the help of two unlikely traveling companions - a jaded, abandoned housecat named Mittens (voice of Susie Essman) and a TV-obsessed hamster named Rhino (voice of Mark Walton) - Bolt discovers he doesn't need superpowers to be a hero.",
  "image": "images/bolt.jpg",
},
{
  "id": "032",
  "title": "Boundin'",
  "year": "2004",
  "description": "On a high mountain plain lives a lamb with wool of such remarkable sheen that he breaks into high-steppin' dance. But there comes a day when he loses his lustrous coat and, along with it, his pride. It takes a wise jackalope - a horn-adorned rabbit - to teach the moping lamb that wooly or not, it's what's inside that'll help him rebound from life's troubles.",
  "image": "images/boundin.jpg",
},
{
  "id": "033",
  "title": "The Bourne Identity",
  "year": "2002",
  "description": "Wounded to the brink of death and suffering from amnesia, Jason Bourne is rescued at sea by a fisherman. With nothing to go on but a Swiss bank account number, he starts to reconstruct his life, but finds that many people he encounters want him dead. Bourne realizes, though, that he has the combat and mental skills of a world-class spy, but who does he work for?",
  "image": "images/the-bourne-identity.jpg",
},
{
  "id": "034",
  "title": "The Bourne Legacy",
  "year": "2012",
  "description": "The fourth installment of the highly successful Bourne series sidelines main character Jason Bourne in order to focus on a fellow estranged assassin Aaron Cross (Jeremy Renner). The story centers on new CIA operative, Aaron Cross as he experiences life-or-death stakes that have been triggered by the previous actions of Jason Bourne. Edward Norton and Rachel Weisz co-star, with Joan Allen and Albert Finney reprising their roles from the previous films.",
  "image": "images/the-bourne-legacy.jpeg",
},
{
  "id": "035",
  "title": "The Bourne Supremacy",
  "year": "2004",
  "description": "When a CIA operation to purchase classified Russian documents is blown by a rival agent, who then shows up in the sleepy seaside village where Bourne and Marie have been living. The pair run for their lives and Bourne, who promised retaliation should anyone from his former life attempt contact, is forced to once again take up his life as a trained assassin to survive.",
  "image": "images/the-bourne-supremacy.jpg",
},
{
  "id": "036",
  "title": "The Bourne Ultimatum",
  "year": "2007",
  "description": "Bourne is brought out of hiding once again by reporter Simon Ross who is trying to unveil Operation Blackbriar, an upgrade to Project Treadstone, in a series of newspaper columns. Information from the reporter stirs a new set of memories, and Bourne must finally uncover his dark past while dodging The Company's best efforts to eradicate him.",
  "image": "images/the-bourne-ultimatum.jpg",
},
{
  "id": "037",
  "title": "Brave",
  "year": "2012",
  "description": "Pixar Animation Studios, the creator of Toy Story 3, whisks you away on an astonishing adventure to an ancient land full of mystery and tradition. Bursting with heart, unforgettable characters and Pixar's signature humor, Brave is incredible entertainment for the whole family. Take a heroic journey with Merida, a skilled archer and headstrong daughter of King Fergus and Queen Elinor. Determined to carve her own path in life, Merida defies an age-old custom sacred to the unruly and uproarious lords of the land. When Merida's actions inadvertently unleash chaos in the kingdom, she must harness all of her skills and resources – including her clever and mischievous triplet brothers – to undo a beastly curse before it's too late, and discover the meaning of true bravery.",
  "image": "images/brave.jpg",
},
{
  "id": "038",
  "title": "A Bug's Life",
  "year": "1998",
  "description": "Life is no picnic for the ants on Ant Island! Each summer a gang of greedy grasshoppers - led by the menacing and manipulative Hopper (Kevin Spacey) - descends upon the colony to demand a hefty portion of the ants' hard-earned harvest and generally make life miserable for this peaceful community. Our hero Flik (Dave Foley), an original thinker out of step with the rest of the more traditionally-minded colony, takes it upon himself to get outside help and mistakenly enlists an unemployed troupe of bug performers from a second-rate flea circus to join the fight against the grasshoppers. Working together in their new-found friendship, the ants and the circus bugs prepare for a climactic confrontation with the grasshoppers. When Flik's plan starts to unravel, the action and comedy turns fast and furious as he attempts to save the colony and his reputation.",
  "image": "images/a-bugs-life.jpeg",
},
{
  "id": "039",
  "title": "Captain Phillips",
  "year": "2013",
  "description": "Captain Phillips is a multi-layered examination of the 2009 hijacking of the U.S. container ship Maersk Alabama by a crew of Somali pirates. Based on a true story, the film focuses on the Alabama’s commanding officer, Captain Richard Phillips (two-time Academy Award®-winner Tom Hanks, Best Actor, 1993, Philadelphia; Best Actor, 1994, Forrest Gump), and the Somali pirate captain, Muse (Barkhad Abdi), who takes him hostage. The two men are set on an unstoppable collision course when Muse and his crew target Phillips’ unarmed ship; in the ensuing standoff, both men will find themselves at the mercy of forces beyond their control.",
  "image": "images/captain-phillips.jpg",
},
{
  "id": "040",
  "title": "Cars",
  "year": "2006",
  "description": "Lightning McQueen, a hotshot rookie race car driven to succeed, discovers that life is about the journey, not the finish line, when he finds himself unexpectedly detoured in the sleepy Route 66 town of Radiator Springs. On route across the country to the big Piston Cup Championship in California to compete against two seasoned pros, McQueen gets to know the town's offbeat characters.",
  "image": "images/cars.jpg",
},
{
  "id": "041",
  "title": "Cars 2",
  "year": "2011",
  "description": "From the creators of Cars comes a new, laugh-out-loud, heart-warming adventure geared for the entire family. Star racecar Lightning McQueen (Owen Wilson) and the incomparable tow truck Mater (Larry the Cable Guy) take their friendship on the road from Radiator Springs to exciting new places when they head overseas to compete in the first-ever World Grand Prix to determine the world’s fastest car. But the road to the championship is filled with plenty of potholes, detours and hilarious surprises when Mater gets caught up in an intriguing adventure of his own: international espionage! It’s turbo-charged action and thrills and “even better than before,” raves Peter Travers of Rolling Stone.",
  "image": "images/cars-2.jpg",
},
{
  "id": "042",
  "title": "Cars 3",
  "year": "2017",
  "description": "Blindsided by a new generation of blazing-fast racers, the legendary Lightning McQueen (voice of Owen Wilson) is suddenly pushed out of the sport he loves. To get back in the game, he’ll need the help of Cruz Ramirez, an eager young race technician with her own plan to win, plus inspiration from the late Fabulous Hudson Hornet and a few unexpected turns. Proving that #95 isn’t through yet will test the heart of a champion on Piston Cup Racing’s biggest stage!",
  "image": "images/cars-3.jpg",
},
{
  "id": "043",
  "title": "Cast Away",
  "year": "2000",
  "description": "Chuck, a top international manager for FedEx, and Kelly, a Ph.D. student, are in love and heading towards marriage. Then Chuck's plane to Malaysia ditches at sea during a terrible storm. He's the only survivor, and he washes up on a tiny island with nothing but some flotsam and jetsam from the aircraft's cargo. Can he survive in this tropical wasteland? Will he ever return to woman he loves?",
  "image": "images/cast-away.jpg",
},
{
  "id": "044",
  "title": "Catch Me If You Can",
  "year": "2002",
  "description": "A true story about Frank Abagnale Jr. who, before his 19th birthday, successfully conned millions of dollars worth of checks as a Pan Am pilot, doctor, and legal prosecutor. An FBI agent makes it his mission to put him behind bars. But Frank not only eludes capture, he revels in the pursuit.",
  "image": "images/catch-me-if-you-can.jpg",
},
{
  "id": "045",
  "title": "A Charlie Brown Christmas",
  "year": "1965",
  "description": "When Charlie Brown complains about the overwhelming materialism that he sees amongst everyone during the Christmas season, Lucy suggests that he become director of the school Christmas pageant. Charlie Brown accepts, but is a frustrating struggle. When an attempt to restore the proper spirit with a forlorn little fir Christmas tree fails, he needs Linus' help to learn the meaning of Christmas.",
  "image": "images/a-charlie-brown-christmas.jpg",
},
{
  "id": "046",
  "title": "Chitty Chitty Bang Bang",
  "year": "1968",
  "description": "In pre-WWI England, a widowed, absent-minded, unsuccessful inventor spruces up a wrecked racing car--which develops the amazing ability to float on water and fly--and plans to take his two children, his girlfriend and the flying automobile on a magical adventure. When the bullying prince of a middle European nation tries to kidnap the auto and its inventor, he grabs the wrong guy and the wrong car. So the adventure becomes a rescue mission that takes the group and their wonderful car to a strange Oz-like world of castles and pirates, where nothing is as it seems. Based on the children's story by Ian Fleming.",
  "image": "images/chitty-chitty-bang-bang.jpg",
},
{
  "id": "047",
  "title": "A Christmas Story",
  "year": "1983",
  "description": "The comic mishaps and adventures of a young boy named Ralph, trying to convince his parents, teachers, and Santa that a Red Ryder B.B. gun really is the perfect Christmas gift for the 1940s.",
  "image": "images/a-christmas-story.jpg",
},
{
  "id": "048",
  "title": "Christopher Robin",
  "year": "2018",
  "description": "In this heartwarming tale from Disney, Christopher Robin, the boy who had countless adventures in the Hundred Acre Wood, has grown up and lost his way. Now it’s up to his spirited and lovable stuffed animals, Winnie The Pooh, Tigger, Piglet, and the rest of the gang, to rekindle their friendship and remind him of endless days of childlike wonder and make-believe.",
  "image": "images/christopher-robbin.jpg",
},
{
  "id": "049",
  "title": "Cinderella",
  "year": "2015",
  "description": "When her father unexpectedly passes away, young Ella finds herself at the mercy of her cruel stepmother and her daughters. Never one to give up hope, Ella's fortunes begin to change after meeting a dashing stranger in the woods.",
  "image": "images/cinderella.jpg",
},
{
  "id": "050",
  "title": "Cloudy With A Chance Of Meatballs",
  "year": "2009",
  "description": "Inventor Flint Lockwood creates a machine that makes clouds rain food, enabling the down-and-out citizens of Chewandswallow to feed themselves. But when the falling food reaches gargantuan proportions, Flint must scramble to avert disaster. Can he regain control of the machine and put an end to the wild weather before the town is destroyed?",
  "image": "images/cloudy-with-a-chance-of-meatballs.jpg",
},
{
  "id": "051",
  "title": "Coco",
  "year": "2017",
  "description": "In Disney•Pixar’s vibrant tale of family, fun and adventure, an aspiring young musician named Miguel (voice of newcomer Anthony Gonzalez) embarks on an extraordinary journey to the magical land of his ancestors. There, the charming trickster Héctor (voice of Gael García Bernal) becomes an unexpected friend who helps Miguel uncover the mysteries behind his family’s stories and traditions.",
  "image": "images/coco.jpg",
},
{
  "id": "052",
  "title": "Cool Runnings",
  "year": "1993",
  "description": "Based on a true story, this is the comedic saga of four Jamaican athletes going to extremes to compete as bobsled racers at the Winter Olympics.",
  "image": "images/cool-runnings.jpg",
},
{
  "id": "053",
  "title": "Curious George 2: Follow That Monkey!",
  "year": "2009",
  "description": "The film chronicles George's adventures as he befriends Kayla, a baby elephant, at a magic circus show and helps her travel across the country to be reunited with her family.Accompanied by his friend, the Man with the Yellow Hat, George travels by foot, train, and truck to reach Kayla's brother and sister in California, only to be accused of elephant-napping and brought all the way back to New York.",
  "image": "images/curious-george-2.jpg",
},
{
  "id": "054",
  "title": "D2: The Mighty Ducks",
  "year": "1994",
  "description": "After Gordon Bombay's hockey comeback is cut short he is named coach of Team USA Hockey for the Junior Goodwill Games. Bombay reunites the Mighty Ducks and introduces a few new players, however, he finds himself distracted by his newfound fame and must regather if the Ducks are to defeat tournament favourites Iceland.",
  "image": "images/d2-the-mighty-ducks.jpg",
},
{
  "id": "055",
  "title": "D3: The Mighty Ducks",
  "year": "1996",
  "description": "The Ducks are offered scholarships at Eden Hall Academy but struggle with their new coach's methods and come under pressure from the board to retain their scholarships before their big game against the Varsity team.",
  "image": "images/d3-the-mighty-ducks.jpeg",
},
{
  "id": "056",
  "title": "The Dark Knight",
  "year": "2008",
  "description": "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
  "image": "images/the-dark-knight.jpg",
},
{
  "id": "057",
  "title": "The Dark Knight Rises",
  "year": "2012",
  "description": "Academy Award® nominee Matt Damon (The Bourne trilogy) stars in this action thriller about a man who glimpses the future Fate has planned for him – and chooses to fight for his own destiny. Battling the powerful Adjustment Bureau across, under and through the streets of New York, he risks his destined greatness to be with the only woman he's ever loved (Emily Blunt: The Young Victoria, The Devil Wears Prada). Based on a story by the legendary Philip K. Dick (Total Recall, Minority Report and Blade Runner), The Adjustment Bureau is “entertaining and thought-provoking”. — Katey Rich, CINEMABLEND.COM",
  "image": "images/the-dark-knight-rises.jpg",
},
{
  "id": "058",
  "title": "Days of Thunder",
  "year": "1990",
  "description": "From the engine roar and fever pitch of professional stock car racing, Days of Thunder explodes with the most spectacular racing action ever captured on film. Tom Cruise plays race car driver Cole Trickle, whose talent and ambition are surpassed only by his burning need to win. Discovered by businessman Tim Daland (Randy Quaid), Cole is teamed with legendary crew chief and car-builder Harry Hogge (Academy Award®-winner Robert Duvall) to race for the Winston Cup at the Daytona 500. A fiery crash nearly ends Cole's career and he must turn to a beautiful doctor (Nicole Kidman) to regain his nerve and the true courage needed to race, to win and to live.",
  "image": "images/days-of-thunder.jpg",
},
{
  "id": "059",
  "title": "Despicable Me",
  "year": "2010",
  "description": "In a happy suburban neighbourhood surrounded by white picket fences with flowering rose bushes, sits a black house with a dead lawn. Unbeknownst to the neighbours, hidden deep beneath this home is a vast secret hideout. Surrounded by an army of tireless, little yellow minions, we discover Gru, planning the biggest heist in the history of the world. He is going to steal the moon (Yes, the moon!) to prove to his Mum that he is better than the other super-villains, especially the new kid on the block, Vector. Gru delights in all things wicked. Armed with his arsenal of shrink rays, freeze guns and battle-ready vehicles for land and air, he vanquishes all who stand in his way. Until the day he encounters the immense will of three little orphaned girls who look at him and see something that no one else has ever seen: a potential dad.",
  "image": "images/despicable-me.jpg",
},
{
  "id": "060",
  "title": "The Devil Wears Prada",
  "year": "2006",
  "description": "Based on the hilarious best-selling novel, this sinfully funny movie stars Academy Award® winner Meryl Streep and Anne Hathaway. As assistant to impossibly demanding New York fashion magazine editor Miranda Priestly (Streep), young Andy Sachs (Hathaway) has landed a job that 'a million girls would die for.' Unfortunately, her heaven-sent appointment as Miranda's personal whipping girl just might be the death of her!",
  "image": "images/the-devil-wears-prada.jpg",
},
{
  "id": "061",
  "title": "Disney Sing Along Songs Disneyland Fun",
  "year": "",
  "description": "",
  "image": "images/disneyland-fun.jpg",
},
{
  "id": "062",
  "title": "Dumbo",
  "year": "2019",
  "description": "From Disney and visionary director Tim Burton, the grand live-action adventure Dumbo expands on the beloved classic story where differences are celebrated, family is cherished and dreams take flight. Circus owner Max Medici (Danny DeVito) enlists former star Holt Farrier (Colin Farrell) and his children to care for a newborn elephant whose oversized ears make him a laughingstock in an already struggling circus. But when they discover that Dumbo can fly, the circus makes an incredible comeback, attracting persuasive entrepreneur V. A. Vandevere (Michael Keaton), who recruits the peculiar pachyderm for his newest, larger-than-life entertainment venture, Dreamland. Dumbo soars to new heights alongside the charming and spectacular aerial artist Colette Marchant (Eva Green)—until Holt learns that beneath its shiny veneer, Dreamland is full of dark secrets.",
  "image": "images/dumbo.jpg",
},
{
  "id": "063",
  "title": "Dunkirk",
  "year": "2017",
  "description": "“Dunkirk” opens as hundreds of thousands of British and Allied troops are surrounded by enemy forces. Trapped on the beach with their backs to the sea they face an impossible situation as the enemy closes in.",
  "image": "images/dunkirk.jpg",
},
{
  "id": "064",
  "title": "Elf",
  "year": "2003",
  "description": "When young Buddy falls into Santa's gift sack on Christmas Eve, he's transported back to the North Pole and raised as a toy-making elf by Santa's helpers. But as he grows into adulthood, he can't shake the nagging feeling that he doesn't belong. Buddy vows to visit Manhattan and find his real dad, a workaholic publisher.",
  "image": "images/elf.jpg",
},
{
  "id": "065",
  "title": "An Extremely Goofy Movie",
  "year": "2000",
  "description": "Join Goofy and his son, Max, in a hip and hilarious movie that kicks up outrageous fun on the road to higher education. It's all extreme sports and a life of freedom as Max sets off for college -- but Goofy misses Max so much he literally falls down on the job. The laughs come fast and furious as he shows up, leisure suit and all, to finish college alongside Max and his friends. When Goofy meets the librarian, they hit if off and spark a stuck-in-the-seventies disco inferno that steals the show. But as Goofy tries to get closer to Max, both must go to the extreme to learn how to live their own lives ... together! From inspired high-energy music to the antics of one of Disney's most beloved dads, AN EXTREMELY GOOFY MOVIE proves that two Goofs are better than one!",
  "image": "images/an-extremely-goofy-movie.jpg",
},
{
  "id": "066",
  "title": "Fantastic Beasts and Where to Find Them",
  "year": "2016",
  "description": "In 1926, Newt Scamander arrives at the Magical Congress of the United States of America with a magically expanded briefcase, which houses a number of dangerous creatures and their habitats. When the creatures escape from the briefcase, it sends the American wizarding authorities after Newt, and threatens to strain even further the state of magical and non-magical relations.",
  "image": "images/fantastic-beasts.jpg",
},
{
  "id": "067",
  "title": "Father of the Bride",
  "year": "1991",
  "description": "Steve Martin turns in a heartwarming and hilarious performance as George Banks, a befuddled father who has a hard time letting go of his young daughter when she unexpectedly announces her plans to wed. Diane Keaton shines as George’s patient, levelheaded wife, while funnyman Martin Short lights up the screen as the off-the-wall wedding consultant. Father Of The Bride vows to deliver fun for the entire family!",
  "image": "images/father-of-the-bride.jpg",
},
{
  "id": "068",
  "title": "Father of the Bride, Part II",
  "year": "1995",
  "description": "Expect crowd-pleasing entertainment when Steve Martin, Diane Keaton and Martin Short return in this hilarious sequel to the comedy smash, Father Of The Bride. Having just married off his cherished daughter (Kimberly Williams), George Banks (Martin) is ready to get footloose and fancy-free! So when his daughter and his wife Nina (Keaton) both announce they are pregnant, George finds himself in one outrageous situation after another - desperately trying to recapture the wild and crazy days of his youth! You'll love every star-filled minute of Father Of The Bride Part II- the riotous comedy hit that delivers double the fun and twice the laughs!",
  "image": "images/father-of-the-bride-2.jpg",
},
{
  "id": "069",
  "title": "Ferris Bueller's Day Off",
  "year": "1986",
  "description": "High-schooler Ferris Bueller knows everyone -- and every trick to faking an illness. So with the entire school convinced he's at death's door, Bueller grabs his girlfriend and best friend and hits the streets of Chicago for a well-deserved day off. Fed-up principal Ed Rooney is determined to catch Bueller and put a premature end to his field trip. But it's tough to outfox Ferris.",
  "image": "images/ferris-bueller.jpg",
},
{
  "id": "070",
  "title": "Fever Pitch",
  "year": "2005",
  "description": "High school teacher Ben Wrightman (Jimmy Fallon) is a good catch. He's charming, funny and great with kids. When he meets Lindsey Meeks (Drew Barrymore), an ambitious business consultant whose spirit is as luminous as her beauty, their attraction is immediate. Sure, they have their differences. She's a workaholic; he loves his summers off. He lives and breathes the Red Sox; she doesn't know Carl Yastrzemski from Johnny Damon. But true love overcomes all...at least until Red Sox spring training rolls around. As Ben's beloved Bosox launch one of the most incredible seasons in baseball history, Ben and Lindsey must decide if they, as a couple, will strike out or fight to keep love alive through extra innings.",
  "image": "images/fever-pitch.jpeg",
},
{
  "id": "071",
  "title": "Field of Dreams",
  "year": "1989",
  "description": "'If you build it, he will come.' With these words, Iowa farmer Ray Kinsella (Kevin Costner) is inspired by a voice he can't ignore to pursue a dream he can hardly believe. Also starring Ray Liotta, James Earl Jones, and Amy Madigan, Field of Dreams is an extraordinary and unforgettable experience that has moved critics and audiences like no other film of its generation. Field of Dreams is a glowing tribute to all who dare to dream.",
  "image": "images/field-of-dreams.jpg",
},
{
  "id": "072",
  "title": "Finding Dory",
  "year": "2016",
  "description": "Disney•Pixar welcomes back everyone’s favorite forgetful blue tang Dory, who’s living happily in the reef with Nemo and Marlin. When Dory suddenly remembers that she has a family out there who may be looking for her, the trio take off on a life-changing adventure across the ocean to California’s Marine Life Institute. In an effort to find her parents, Dory enlists the help of Hank, a cantankerous octopus; Bailey, a beluga whale who’s convinced his biological sonar skills are on the fritz; and Destiny, a nearsighted whale shark. Navigating the complex inner workings of the MLI, Dory and her friends discover the magic within their flaws, friendships and family.",
  "image": "images/finding-dory.jpg",
},
{
  "id": "073",
  "title": "Finding Nemo",
  "year": "2003",
  "description": "A tale which follows the comedic and eventful journeys of two fish, the fretful Marlin and his young son Nemo, who are separated from each other in the Great Barrier Reef when Nemo is unexpectedly taken from his home and thrust into a fish tank in a dentist's office overlooking Sydney Harbor. Buoyed by the companionship of a friendly but forgetful fish named Dory, the overly cautious Marlin embarks on a dangerous trek and finds himself the unlikely hero of an epic journey to rescue his son.",
  "image": "images/finding-nemo.jpeg",
},
{
  "id": "074",
  "title": "First Kid",
  "year": "1996",
  "description": "Some say that to be the leader of a country is one of the loneliest jobs in the world. But being the child of a world leader can be doubly so. Constantly surrounded by security officers, restricted in movements and having almost every waking moment carefully monitored makes normalcy an impossibility. No one knows this better than young Luke Davenport, the son of U.S. President Davenport. He vents his loneliness, frustration and feelings of isolation from family and friends by being a brat to his private Secret Service agent. When the agent snaps from the strain in front of the First Lady, a new agent is assigned to Luke. He turns out to be the enormous Sam Simms, a bit of a rogue who managed to rise through the ranks by sheer determination rather than strict adherence to Secret-Service protocol. At first, Luke tries all his old tricks upon Sam. But instead of getting angry, Sam seems to actually understand.",
  "image": "images/first-kid.jpeg",
},
{
  "id": "075",
  "title": "First Man",
  "year": "2018",
  "description": "From Oscar®-winning director Damien Chazelle and star Ryan Gosling, First Man is the riveting and triumphant story behind the first manned mission to the moon, focusing on Neil Armstrong and the events leading to the extraordinary Apollo 11 flight—one of the most dangerous missions in history.",
  "image": "images/first-man.jpg",
},
{
  "id": "076",
  "title": "Footloose",
  "year": "1984",
  "description": "Footloose jumps with spirit, dazzling dance numbers and an electrifying musical score. It portrays the timeless struggle between innocent pleasure and rigid morality, when city-boy Ren McCormick (Kevin Bacon) finds himself in an uptight Midwestern town where dancing has been banned. Ren revolts with best friend Willard (Chris Penn) and the minister's daughter (Lori Singer).",
  "image": "images/footloose.jpg",
},
{
  "id": "077",
  "title": "Ford v Ferrari",
  "year": "2019",
  "description": "Academy Award® Winners Matt Damon and Christian Bale star in FORD v FERRARI, based on the true story of visionary American car designer Carroll Shelby (Damon) and fearless British-born driver Ken Miles (Bale), who together build a revolutionary race car for Ford Motor Company and take on the dominating race cars of Enzo Ferrari at the 24 Hours of Le Mans in France in 1966. Based on the true story.",
  "image": "images/ford-v-ferrari.jpg",
},
{
  "id": "078",
  "title": "The Founder",
  "year": "2017",
  "description": "Directed by John Lee Hancock (SAVING MR. BANKS), THE FOUNDER features the true story of how Ray Kroc (Michael Keaton), a struggling salesman from Illinois, met Mac and Dick McDonald, who were running a burger operation in 1950s Southern California. Kroc was impressed by the brothers' speedy system of making the food and saw franchise potential. Writer Robert Siegel (THE WRESTLER) details how Kroc maneuvered himself into a position to be able to pull the company from the brothers and create a billion-dollar empire. The film also stars Laura Dern as Ray Kroc’s first wife Ethel; John Carroll Lynch as Mac McDonald and Nick Offerman as Dick McDonald.",
  "image": "images/the-founder.jpeg",
},
{
  "id": "079",
  "title": "Frozen",
  "year": "201f3",
  "description": "In “Frozen,” fearless optimist Anna teams up with rugged mountain man Kristoff and his loyal reindeer Sven in an epic journey, encountering Everest-like conditions, mystical trolls and a hilarious snowman named Olaf in a race to find Anna's sister Elsa, whose icy powers have trapped the kingdom of Arendelle in eternal winter.",
  "image": "images/frozen.jpg",
},
{
  "id": "080",
  "title": "Frozen II",
  "year": "2019",
  "description": "Why was Elsa born with magical powers? What truths about the past await Elsa as she ventures into the unknown to the enchanted forests and dark seas beyond Arendelle? The answers are calling her but also threatening her kingdom. Together with Anna, Kristoff, Olaf and Sven, she'll face a dangerous but remarkable journey. In Frozen, Elsa feared her powers were too much for the world. In Frozen II, she must hope they are enough.",
  "image": "images/frozen-2.jpg",
},
{
  "id": "081",
  "title": "Glory Road",
  "year": "2006",
  "description": "In 1966, Texas Western coach Don Haskins led the first all-black starting line-up for a college basketball team to the NCAA national championship.",
  "image": "images/glory-road.jpeg",
},
{
  "id": "082",
  "title": "The Godfather",
  "year": "1972",
  "description": "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
  "image": "images/the-godfather.jpg",
},
{
  "id": "083",
  "title": "Gone In 60 Seconds",
  "year": "2000",
  "description": "Randall 'Memphis' Raines long ago abandoned his life of crime, but after an ominous visit from an old friend, he finds he has no choice but to return to what he does best - stealing cars - in order to save his brother's life. It all comes down to one night, 50 cars and a contract. A true automobile aficionado, Memphis has a burning passion for cars. Fuel-injected, high-performance, v-8, v-12, turbo-charged, loaded or stripped to the bare essentials, he knows and loves every nut and bolt, every gleaming piece of chrome. Memphis is a car thief of legendary proportion. No fancy lock or alarm can stop him; your car will be there and gone in 60 seconds. For years, Memphis eluded the law while boosting every make and model imaginable, with the exception of one elusive car, his beloved Eleanor, a 1967 Shelby Mustang GT 500. When the heat became too intense, he left everything and everyone he loved to find a different life. But when his kid brother tries to follow in his footsteps only to become dangerously embroiled in a high-stakes caper, Memphis is sucked back into his old life, tearing up the streets for one last death-defying heist.",
  "image": "images/gone-in-60-seconds.jpg",
},
{
  "id": "084",
  "title": "A Goofy Movie",
  "year": "1995",
  "description": "Max Goof's embarrassing dad Goofy is taking him to a cross-country road trip for a fishing vacation at Lake Destiny, Idaho. Goofy went to the same place with his father when he was Max's age. This vacation is Max's worst nightmare, and it couldn't have happened at a worse time- his original plan was to escort his dream date Roxanne to her friend Stacey's end-of-year-party to see a Powerline concert in Los Angeles on a big-screen TV. But Goofy refuses to let Max skip out on the vacation, so Max has no choice but to cancel the date with Roxanne.",
  "image": "images/a-goofy-movie.jpg",
},
{
  "id": "085",
  "title": "The Goonies",
  "year": "1985",
  "description": "The combined talents of two of today's most prominent filmmakers -  Steven Spielberg and Richard Donner - created this box office hit that delights the young and the young at heart. When a group of ordinary kids discover a secret treasure map, their sleepy seaport lives are suddenly transformed into a fun-filled, roller-coaster ride filled with heart-pounding adventure and peril.",
  "image": "images/the-goonies.jpg",
},
{
  "id": "086",
  "title": "The Greatest Game Ever Played",
  "year": "2005",
  "description": "From Walt Disney Pictures comes The Greatest Game Ever Played . . . the crowd-pleasing underdog epic that's based on an inspirational true story! Young amateur golfer Francis Ouimet has nothing but talent and a seemingly impossible dream to challenge the world's greatest player, his idol Harry Vardon. Soon, with the help of his spunky 10-year-old caddy Eddie, Francis boldly breaks down all barriers with a thrilling display of unrivaled drive, skill, and heart . . . and challenges the golf pro for the U.S. Open Championship!",
  "image": "images/the-greatest-game-ever-played.jpg",
},
{
  "id": "087",
  "title": "The Goonies",
  "year": "2017",
  "description": "THE GREATEST SHOWMAN is an original musical inspired by the life of P.T. Barnum, starring Hugh Jackman. Barnum was a visionary who rose from nothing to create the “Greatest Show on Earth,” a spectacle and celebration of his larger-than-life imagination that captivated audiences around the globe.",
  "image": "images/the-greatest-showman.jpg",
},
{
  "id": "088",
  "title": "The Guardian",
  "year": "2006",
  "description": "Kevin Costner and Ashton Kutcher star in THE GUARDIAN, the powerful, action-packed drama that takes you inside the never-before-seen world of the elite Coast Guard Rescue Swimmers. Reeling with grief in the wake of a mission gone tragically wrong, legendary Rescue Swimmer Ben Randall (Costner) is given a mission he doesn't want - training raw recruits. Once there, he knocks heads with cocky Jake Fischer (Kutcher), a swimming champ driven by a painful secret, who's more interested in breaking Ben's records than saving lives. But Ben also sees Jake has what it takes to be the best of the best. Filled with spectacular rescues in the lethal waters of the Bering Sea, THE GUARDIAN is a riveting and compelling story that dives straight into the heart and soul of real heroes, the unsung guardians of the sea.",
  "image": "images/the-guardian.jpeg",
},
{
  "id": "089",
  "title": "Guardians of the Galaxy",
  "year": "2014",
  "description": "From Marvel, the studio that brought you the global blockbuster franchises of Iron Man, Thor, Captain America and The Avengers, comes a new team—the Guardians of the Galaxy. An action-packed, epic space adventure, Marvel’s “Guardians of the Galaxy” expands the Marvel Cinematic Universe into the cosmos, where brash adventurer Peter Quill finds himself the object of an unrelenting bounty hunt after stealing a mysterious orb coveted by Ronan, a powerful villain with ambitions that threaten the entire universe. To evade the ever-persistent Ronan, Quill is forced into an uneasy truce with a quartet of disparate misfits—Rocket, a gun-toting raccoon, Groot, a tree-like humanoid, the deadly and enigmatic Gamora and the revenge-driven Drax the Destroyer. But when Quill discovers the true power of the orb and the menace it poses to the cosmos, he must do his best to rally his ragtag rivals for a last, desperate stand—with the galaxy’s fate in the balance.",
  "image": "images/guardians-of-the-galaxy.jpg",
},
{
  "id": "090",
  "title": "Guardians of the Galaxy Vol. 2",
  "year": "2017",
  "description": "Set to the sonic backdrop of Awesome Mixtape #2, Marvel Studios’ Guardians of the Galaxy Vol. 2 continues the team’s adventures as they traverse the outer reaches of the cosmos. The Guardians must fight to keep their newfound family together as they unravel the mystery of Peter Quill’s true parentage. Old foes become new allies and characters from the classic comics come to their aid as the Marvel Cinematic Universe continues to expand.",
  "image": "images/guardians-of-the-galaxy-2.jpg",
},
{
  "id": "091",
  "title": "Hairspray",
  "year": "2007",
  "description": "It's 1962, and change is in the air in Baltimore. Tracy Turnblad, a big girl with big hair and an even bigger heart, has only one passion--to dance. She wins a spot on the local TV dance program, 'The Corny Collins Show' and is transformed overnight from outsider to irrepressible teen celebrity. But can the trendsetting Tracy win the heart of teen-dream Link Larkin and stand up for what she believes in, despite the program's scheming stage manager? All she needs is her best friend Penny, a toe- tappin' beat - and a little HAIRSPRAY!",
  "image": "images/hairspray.jpg",
},
{
  "id": "092",
  "title": "Hancock",
  "year": "2008",
  "description": "Hancock is a down-and-out superhero who's forced to employ a PR expert to help repair his image when the public grows weary of all the damage he's inflicted during his lifesaving heroics. The agent's idea of imprisoning the antihero to make the world miss him proves successful, but will Hancock stick to his new sense of purpose or slip back into old habits?",
  "image": "images/hancock.jpg",
},
{
  "id": "093",
  "title": "Happy Gilmore",
  "year": "1996",
  "description": "Failed hockey player-turned-golf whiz Happy Gilmore -- whose unconventional approach and antics on the grass courts the ire of rival Shooter McGavin -- is determined to win a PGA tournament so he can save his granny's house with the prize money. Meanwhile, an attractive tour publicist tries to soften Happy's image.",
  "image": "images/happy-gilmore.jpg",
},
{
  "id": "094",
  "title": "Harry Potter and the Deathly Hallows: Part 2",
  "year": "2011",
  "description": "'Harry Potter and the Deathly Hallows - Part 2,' is the final adventure in the Harry Potter film series. The much-anticipated motion picture event is the second of two full-length parts. In the epic finale, the battle between the good and evil forces of the wizarding world escalates into an all-out war. The stakes have never been higher and no one is safe. But it is Harry Potter who may be called upon to make the ultimate sacrifice as he draws closer to the climactic showdown with Lord Voldemort. It all ends here.",
  "image": "images/harry-potter-deathly-hallows-part-2.jpg",
},
{
  "id": "095",
  "title": "Harry Potter and the Sorcerer's Stone",
  "year": "2001",
  "description": "Harry Potter has lived under the stairs at his aunt and uncle's house his whole life. But on his 11th birthday, he learns he's a powerful wizard -- with a place waiting for him at the Hogwarts School of Witchcraft and Wizardry. As he learns to harness his newfound powers with the help of the school's kindly headmaster, Harry uncovers the truth about his parents' deaths -- and about the villain who's to blame.",
  "image": "images/harry-potter-sorcerers-stone.jpg",
},
{
  "id": "096",
  "title": "Harry Potter and the Chamber of Secrets",
  "year": "2002",
  "description": "Everyone's favorite novice wizard, Harry Potter, continues his high-flying adventures at Hogwarts. This time around, Harry ignores warnings not to return to school - that is, if he values his life - to investigate a mysterious series of attacks with Ron and Hermione.",
  "image": "images/harry-potter-chamber-of-secrets.jpg",
},
{
  "id": "097",
  "title": "Harry Potter and the Prisoner of Azkaban",
  "year": "2004",
  "description": "Harry, Ron and Hermione return to Hogwarts for a third adventure-and-magic-filled year in this follow-up to the first two Potter blockbusters. Harry comes face-to-face with danger yet again, this time in the form of escaped convict Sirius Black. In a bid for help, Harry turns to sympathetic Professor Lupin -- but will it be enough?",
  "image": "images/harry-potter-prizoner-of-azkaban.jpg",
},
{
  "id": "098",
  "title": "Harry Potter and the Goblet of Fire",
  "year": "2005",
  "description": "Young wizard Harry Potter starts his fouth year at Hogwarts, competes in the treacherous Tri-Wizard Tournament and faces the evil Lord Voldemort. Friends Ron and Hermione help Harry manage the pressure … but Voldemort lurks, awaiting his chance to destroy Harry and all that he stands for.",
  "image": "images/harry-potter-goblet-of-fire.jpg",
},
{
  "id": "099",
  "title": "Harry Potter and the Order of the Phoenix",
  "year": "2007",
  "description": "Returning for his fifth year of study at the venerable Hogwarts School of Witchcraft and Wizardry, the ever-maturing Harry Potter is stunned to find that his warnings about the return of Lord Voldemort have been ignored. Left with no choice, Harry takes matters into his own hands, training a small group of students -- dubbed 'Dumbledore's Army' -- to defend themselves against the dark arts.",
  "image": "images/harry-potter-order-of-the-phoenix.jpg",
},
{
  "id": "100",
  "title": "Harry Potter and the Half-Blood Prince",
  "year": "2009",
  "description": "The sixth year at Hogwarts School of Witchcraft and Wizardry kicks off with a bang for young Harry Potter when he inadvertently discovers a mysterious book that sheds light on the sordid life of the evil Lord Voldemort. Preparing for inevitable battle, Harry and Dumbledore turn to professor Horace Slughorn for help in pinpointing the weakness in Voldemort's forces.",
  "image": "images/harry-potter-half-blood-prince.jpg",
},
{
  "id": "101",
  "title": "Harry Potter and the Deathly Hallows: Part 1",
  "year": "2010",
  "description": "The end begins as Harry, Ron, and Hermione walk away from their last year at Hogwarts to find and destroy the remaining Horcruxes, putting an end to Voldemort's bid for immortality. But with Harry's beloved Dumbledore dead and Voldemort's unscrupulous Death Eaters on the loose, the world is more dangerous than ever.",
  "image": "images/harry-potter-deathly-hallows-part-1.jpg",
},
{
  "id": "102",
  "title": "Heavy Weights",
  "year": "1995",
  "description": "11-year-old Gerald 'Gerry' Garner lives in Hendersonville, North Carolina, and he's overweight. Gerry's parents Maury and Mrs. Garner decide to send Gerry to Camp Hope, a camp for overweight boys. The camp is owned by kindly Harvey Bushkin and his equally kind wife Alice Bushkin. When the Bushkins declare bankruptcy and decide to step down as the camp's owners, the camp is bought by a wacko named Tony Perkis. Tony plans to force the campers to lose as much weight as they can, and he also intends to document the marathon shedding of weight and use it for an infomercial for his slenderizing program. In the eyes of the campers, Tony has made Camp Hope a living hell. As Gerry and counselor Pat Finley lead the efforts to overthrow Tony, the campers prepare for the Apache Relay against arch rival Camp MVP. The Apache Relay is a kind of race in which Camp Hope has never defeated Camp MVP before.",
  "image": "images/heavyweights.jpg",
},
{
  "id": "103",
  "title": "Hercules",
  "year": "1997",
  "description": "An outrageous odyssey of fun, fantasy, and adventure unfolds in the hilarious hit film Hercules. Taken from the gods as a newborn, adopted on earth, Hercules becomes an awkward teenage pillar of strength. Trying to fit in, he discovers his dad is Zeus and home is Mount Olympus -- if he can move from 'zero' to true hero! Hercules teams with babyhood pal Pegasus, the flying stallion, and Phil -- a feisty personal trainer -- for the mission. But it's no easy task as he must match wits with Grecian beauty Meg and a comical hothead named Hades. With the help of Pain and Panic, Hades plans to rule the Universe with only Hercules standing in his way! With a bold animation style, colossal voice cast, and spectacular music, Hercules is unmatched in strength -- delivering something for everyone.",
  "image": "images/hercules.jpeg",
},
{
  "id": "104",
  "title": "Hidden Figures",
  "year": "2016",
  "description": "The incredible untold true story of Katherine Johnson (Taraji P. Henson), Dorothy Vaughan (Octavia Spencer) & Mary Jackson (Janelle Monae)—brilliant African-American women working at NASA, who served as the brains behind one of the greatest operations in history: the launch of astronaut John Glenn into orbit. This stunning achievement galvanized the world and inspired generations to dream big.",
  "image": "images/hidden-figures.jpg",
},
{
  "id": "105",
  "title": "Hitch",
  "year": "2005",
  "description": "Dating coach Alex 'Hitch' Hitchens mentors a bumbling client, Albert, who hopes to win the heart of the glamorous Allegra Cole. While Albert makes progress, Hitch faces his own romantic setbacks when proven techniques fail to work on Sara Melas, a tabloid reporter digging for dirt on Allegra Cole's love life. When Sara discovers Hitch's connection to Albert – now Allegra's boyfriend – it threatens to destroy both relationships.",
  "image": "images/hitch.jpg",
},
{
  "id": "106",
  "title": "The Hobbit: An Unexpected Journey",
  "year": "2012",
  "description": "Bilbo Baggins, a hobbit enjoying his quiet life, is swept into an epic quest by Gandalf the Grey and thirteen dwarves who seek to reclaim their mountain home from Smaug, the dragon.",
  "image": "images/the-hobbit.jpg",
},
{
  "id": "107",
  "title": "Hocus Pocus",
  "year": "1993",
  "description": "Hollywood superstar Bette Midler (Beaches) joins Sarah Jessica Parker (Honeymoon in Vegas) and Kathy Najimy (Sister Act) as three outlandishly wild witches who return from 17th Century Salem for a night of zany fun and comic chaos. After they're accidentally conjured up by some unsuspecting pranksters, the tricky 300-year-old trio sets out to cast a spell on the town and reclaim their youth - but first they must outwit three pesky kids who are determined to foil their scheme! Loaded with bewitching laughs and magical special effects, 'Hocus Pocus' is an outrageous comedy that's sure to entertain everyone.",
  "image": "images/hocus-pocus.jpg",
},
{
  "id": "108",
  "title": "Home Alone",
  "year": "1990",
  "description": "Eight-year-old Kevin McCallister makes the most of the situation after his family unwittingly leaves him behind when they go on Christmas vacation. But when a pair of bungling burglars set their sights on Kevin's house, the plucky kid stands ready to defend his territory. By planting booby traps galore, adorably mischievous Kevin stands his ground as his frantic mother attempts to race home before.",
  "image": "images/home-alone.jpg",
},
{
  "id": "109",
  "title": "Home Alone 2: Lost In New York",
  "year": "1999",
  "description": "Great news – Kevin McCallister (Macaulay Culkin) is spending the holidays in New York City! Bad news – his parents are spending them in Florida! Separated once again from his family, Kevin manages to find food, lodging and fun using his dad’s credit card. But his big-spending solo act takes a dangerous turn when the Wet Bandits, Harry and Marv (Joe Pesci and Daniel Stern), escape prison and also land in the Big Apple. Now, Kevin must outrun and outprank them again in this high-flying adventure with twice the ingenuity, twice the kid power and twice the laughs as the original!",
  "image": "images/home-alone-2.jpg",
},
{
  "id": "110",
  "title": "Hook",
  "year": "1991",
  "description": "A high-flying adventure from the magic of Steven Spielberg, HOOK stars Robin Williams as a grown-up Peter Pan and Dustin Hoffman as the infamous Captain Hook. Joining the fun is Julia Roberts as Tinkerbell, Bob Hoskins as the pirate Smee, and Maggie Smith as Granny Wendy Darling, who must convince the middle-aged lawyer, Peter Banning, that he was once the legendary Peter Pan. And so the adventure begins anew, with Peter off to Neverland to save his two children from Captain Hook. Along the way, he rediscovers the power of imagination, of friendship, and of magic.",
  "image": "images/hook.jpg",
},
{
  "id": "111",
  "title": "Hoosiers",
  "year": "1986",
  "description": "A classic tale of redemption, this film features a volatile coach and a former star player-turned alcoholic leading a small-town basketball team on an improbable run to the Indiana high school championship game. Coach Norman Dale encounters several hurdles in his path: a feisty teacher determined to keep the best player from going out for the team, a town chock full of second-guessing fathers, and a group of undisciplined athletes. Story inspired by the Milan (Indiana) Indians' state title of 1954. Nominated for two Oscars and hailed by Sports Illustrated and ESPN as one of the best sports movies of all time, this triumphant tale of a high school basketball team's long-shot attempt to win the state features 'fast-break cinematography' that catches the pace of the game.",
  "image": "images/hoosiers.jpg",
},
{
  "id": "112",
  "title": "The Goonies",
  "year": "2011",
  "description": "Hugo is an orphan boy living in the walls of a train station in 1930s Paris. He learned to fix clocks and other gadgets from his father and uncle which he puts to use keeping the train station clocks running. The only thing that he has left that connects him to his dead father is an automaton (mechanical man) that doesn't work without a special key which Hugo needs to find to unlock the secret he believes it contains. On his adventures, he meets with a shopkeeper, George Melies, who works in the train station and his adventure-seeking god-daughter. Hugo finds that they have a surprising connection to his father and the automaton, and he discovers it unlocks some memories the old man has buried inside regarding his past.",
  "image": "images/hugo.jpg",
},
{
  "id": "113",
  "title": "The Hunger Games",
  "year": "2012",
  "description": "Based on the best-selling books by Suzanne Collins, THE HUNGER GAMES is the first film in the franchise. Every year in the ruins of what was once North America, the Capitol of the nation of Panem forces each of its twelve districts to send a teenage boy and girl to compete in the Hunger Games. Sixteen-year-old Katniss Everdeen volunteers in her younger sister’s place and must rely upon her sharp instincts when she’s pitted against highly trained Tributes who have prepared their entire lives. If she’s ever to return home to District 12, Katniss must make impossible choices in the arena that weigh survival against humanity and life against love.",
  "image": "images/the-hunger-games.jpg",
},
{
  "id": "114",
  "title": "The Hunger Games: Catching Fire",
  "year": "2013",
  "description": "Katniss Everdeen has returned home safe after winning the 74th Annual Hunger Games along with fellow tribute Peeta Mellark. Winning means that they must turn around and leave their family and close friends, embarking on a 'Victor's Tour' of the districts. Along the way Katniss senses that a rebellion is simmering, but the Capitol is still very much in control as President Snow prepares the 75th Annual Hunger Games (The Quarter Quell) - a competition that could change Panem forever.",
  "image": "images/the-hunger-games-catching-fire.jpg",
},
{
  "id": "115",
  "title": "The Hunger Games: Mockingjay - Part 1",
  "year": "2014",
  "description": "Katniss Everdeen reluctantly becomes the symbol of a mass rebellion against the autocratic Capitol.",
  "image": "images/the-hunger-games-mockingjay-part-1.jpg",
},
{
  "id": "116",
  "title": "The Hunger Games: Mockingjay - Part 2",
  "year": "2015",
  "description": "With the nation of Panem in a full scale war, Katniss confronts President Snow in the final showdown. Teamed with a group of her closest friends – including Gale, Finnick, and Peeta – Katniss goes off on a mission with the unit from District 13 as they risk their lives to stage an assassination attempt on President Snow who has become increasingly obsessed with destroying her. The mortal traps, enemies, and moral choices that await Katniss will challenge her more than any arena she faced in The Hunger Games.",
  "image": "images/the-hunger-games-mockingjay-part-2.jpg",
},
{
  "id": "117",
  "title": "The Hunt for Red October",
  "year": "1990",
  "description": "Based on Tom Clancy's bestseller, directed by John McTiernan (Die Hard) and starring Sean Connery and Alec Baldwin, The Hunt For Red October seethes with high-tech excitement and sweats with the tension of men who hold Doomsday in their hands. A new technologically-superior Soviet nuclear sub, the Red October, is heading for the U.S. coast under the command of Captain Marko Ramius (Connery). The American government thinks Ramius is planning to attack. A lone CIA analyst (Baldwin) has a different idea: he thinks Ramius is planning to defect, but he has only a few hours to find him and prove it - because the entire Russion naval and air commands are trying to find him, too. The hunt is on!",
  "image": "images/the-hunt-for-red-october.jpg",
},
{
  "id": "118",
  "title": "The Adjustment Bureau",
  "year": "2011",
  "description": "Academy Award® nominee Matt Damon (The Bourne trilogy) stars in this action thriller about a man who glimpses the future Fate has planned for him – and chooses to fight for his own destiny. Battling the powerful Adjustment Bureau across, under and through the streets of New York, he risks his destined greatness to be with the only woman he's ever loved (Emily Blunt: The Young Victoria, The Devil Wears Prada). Based on a story by the legendary Philip K. Dick (Total Recall, Minority Report and Blade Runner), The Adjustment Bureau is “entertaining and thought-provoking”. — Katey Rich, CINEMABLEND.COM",
  "image": "images/the-adjustment-bureau.jpg",
},];
